services:
  broker:
    container_name: thingsboard-broker
    image: rabbitmq:3.13.0-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_HOST=broker
      - RABBITMQ_DEFAULT_PORT=5672
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5
      timeout: 5s

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - timescale_data:/home/postgres/pgdata

  thingsboard:
    image: astrikos-thingsboard
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: thingsboard
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/thingsboard
    depends_on:
      - broker
      - timescaledb

volumes:
  timescale_data:
